import { Card, CardHeader, CardTitle, CardContent } from '../components/Card';
import { FileText, Download, Calendar, ExternalLink } from 'lucide-react';

export function Reports() {
  const reports = [
    { id: '1', title: 'Q3 Macro Crypto Regime Analysis', date: '2023-10-01', author: 'AI Research Agent', type: 'PDF' },
    { id: '2', title: 'Momentum Breakdown in NVIDIA', date: '2023-09-15', author: 'System', type: 'HTML' },
    { id: '3', title: 'Cross-Asset Correlation Shift', date: '2023-08-22', author: 'AI Research Agent', type: 'PDF' },
  ];

  return (
    <div className="flex flex-col h-full space-y-6 animate-fade-in">
      <div className="flex justify-between items-start">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Research Reports</h1>
          <p className="text-sm text-text-muted mt-1">
            Access and download historical analysis and AI-generated intelligence briefings.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {reports.map((report) => (
          <Card key={report.id} className="hover:border-primary/50 transition-colors group cursor-pointer">
            <CardHeader className="py-4 border-b border-border/50">
              <CardTitle className="text-sm font-bold leading-tight group-hover:text-primary transition-colors">
                {report.title}
              </CardTitle>
            </CardHeader>
            <CardContent className="p-4 space-y-4">
              <div className="flex flex-col gap-2 text-xs text-text-muted">
                <div className="flex items-center">
                  <Calendar size={14} className="mr-2" />
                  {report.date}
                </div>
                <div className="flex items-center">
                  <FileText size={14} className="mr-2" />
                  Generated by: <span className="text-text-main ml-1 font-medium">{report.author}</span>
                </div>
              </div>
              
              <div className="pt-2 border-t border-border flex justify-between items-center">
                <span className="text-[10px] uppercase font-bold bg-surface-highlight px-2 py-1 rounded">
                  {report.type}
                </span>
                <div className="flex gap-2">
                  <button className="p-1.5 text-text-muted hover:text-primary hover:bg-surface-hover rounded transition-colors">
                    <ExternalLink size={16} />
                  </button>
                  <button className="p-1.5 text-text-muted hover:text-primary hover:bg-surface-hover rounded transition-colors">
                    <Download size={16} />
                  </button>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
